@echo off
REM RUN_APP_DEPLOY.bat - Deploy Vic's Figma-drawn body-zone polygons to GitHub Pages.
REM Generated by Cowork on 2026-05-01.
REM ASCII only. No smart quotes / em-dashes.

cd /d "C:\Users\Victor\Documents\Claude\Projects\PPWELLNESS - Website and Brand\ppw-app"

echo ============================================================
echo PPW App Deploy - Figma Body-Zone Polygon Integration
echo ============================================================
echo.

REM Clear any stale lock from a crashed git process
if exist .git\index.lock (
    echo Removing stale .git\index.lock ...
    del /f /q .git\index.lock
)

echo.
echo --- Staging files ---
git add src\data.js
git add tools\extract-zones.mjs
git add tools\figma-to-data.mjs
git add tools\zones.generated.js
git add assets\figma-exports\front.svg
git add assets\figma-exports\back.svg
git add assets\figma-exports\back_layer_names.json
git add assets\figma-exports\paths_meta.json
git add RUN_APP_DEPLOY.bat

echo.
echo --- Status ---
git status --short

echo.
echo --- Committing ---
git commit -m "feat(BodyMap): integrate Vic's Figma-drawn polygon hotspots - 34 zones across FRONT + BACK" -m "Source: Figma file C7CyNdQpC5o2OHCeUJyT4K (FRONT and BACK frames). Vic hand-drew polygons over the anatomical figures, then exported each frame as SVG. tools/extract-zones.mjs maps the human-readable layer names to canonical zone codes (with anatomical L/R flipped to image L/R for FRONT view), parses path vertices, and applies convex hull for clean click-hotspot geometry. 15 zones FRONT, 19 zones BACK. Dropped per Vic decisions: Solar Plexus (no canonical zone), Scapula L/R (upper-back covers), Jaw L/R (not drawn). Auto-fixed duplicate Gluteal L typo to gluteal-right."

echo.
echo --- Pulling latest with rebase ---
git pull --rebase origin main

echo.
echo --- Pushing to origin/main ---
git push origin main

echo.
echo ============================================================
echo Done. GitHub Actions will auto-deploy to GitHub Pages.
echo Live URL: https://victorcassiusoffice-sketch.github.io/ppw-fascia-app/
echo Wait ~2 minutes, then verify in browser.
echo ============================================================
echo.
pause
